/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-background': '#1b1c1c',
        'tertiary-container': '#5d5f61',
        'primary-fixed-dim': '#bec2ff',
        'inverse-primary': '#bec2ff',
        'on-primary-fixed': '#00026c',
        'secondary-fixed': '#e1e0ff',
        primary: '#3239a3',
        'on-surface-variant': '#454653',
        'primary-container': '#4b53bc',
        'on-tertiary-fixed': '#1a1c1d',
        tertiary: '#464749',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f3f0ef',
        secondary: '#56589a',
        'surface-variant': '#e4e2e1',
        'on-primary-fixed-variant': '#3239a3',
        'on-secondary-fixed-variant': '#3e4080',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#303030',
        'tertiary-fixed-dim': '#c6c6c8',
        'surface-bright': '#fcf9f8',
        'outline-variant': '#c6c5d5',
        'on-primary-container': '#d5d6ff',
        'surface-container-highest': '#e4e2e1',
        'on-tertiary-fixed-variant': '#454749',
        'on-surface': '#1b1c1c',
        'on-secondary-container': '#424485',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#c0c1ff',
        'on-tertiary-container': '#d9d9db',
        'surface-container-low': '#f6f3f2',
        'on-error-container': '#93000a',
        'surface-container': '#f0eded',
        surface: '#fcf9f8',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#e2e2e4',
        outline: '#767684',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'secondary-container': '#b3b5fe',
        background: '#fcf9f8',
        'surface-tint': '#4b53bc',
        'surface-dim': '#dcd9d9',
        'surface-container-high': '#eae7e7',
        'primary-fixed': '#e0e0ff',
        'on-secondary-fixed': '#101053',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        xs: '4px',
        lg: '24px',
        sm: '8px',
        'margin-desktop': '32px',
        xl: '32px',
        gutter: '20px',
        md: '16px',
        unit: '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      animation: {
        'content-entrance': 'contentEntrance 0.3s cubic-bezier(0.4,0,0.2,1) both',
        'fluid-entrance': 'slideUpFade 0.6s cubic-bezier(0.4,0,0.2,1) both',
      },
      keyframes: {
        contentEntrance: {
          from: { opacity: 0, transform: 'translateY(8px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        slideUpFade: {
          from: { opacity: 0, transform: 'translateY(12px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
